export const prompts = [
  "Alimente-se bem, viva melhor.",
  "Saúde à mesa, vida em harmonia.",
  "Nutrição inteligente, vida saudável.",
  "Sua jornada para uma vida mais saudável começa aqui.",
  "Escolhas saudáveis, futuro brilhante.",
  "Do campo à mesa, com saúde e sabor.",
  "Transforme sua alimentação, transforme sua vida.",
  "Coma bem, sinta-se bem, viva bem.",
  "Conhecimento é poder, especialmente no prato.",
  "Nutrindo corpos, cultivando saúde.",
  "Cultive o hábito de uma alimentação saudável.",
  "Cada refeição é uma oportunidade para nutrir seu corpo.",
  "A saúde começa no prato.",
  "Escolhas alimentares conscientes fortalecem seu bem-estar.",
  "Seu corpo merece o melhor combustível: comida saudável.",
  "O equilíbrio está na diversidade dos alimentos.",
  "Invista em sua saúde com cada garfada.",
  "Sua dieta reflete seu estilo de vida.",
  "Coma cores para uma saúde vibrante.",
  "A alimentação saudável é uma forma de autocuidado.",
  "Transforme sua cozinha em um laboratório de saúde.",
  "O segredo está em ouvir as necessidades do seu corpo.",
  "Priorize alimentos frescos e naturais.",
  "Nutrição é a base para uma vida longa e ativa.",
  "Seu prato é a tela da sua saúde.",
  "Coma menos do que o que quer e mais do que o que precisa.",
  "A moderação é a chave para uma dieta equilibrada.",
  "Fuja dos extremos, busque o equilíbrio.",
  "Um corpo saudável é construído com escolhas saudáveis.",
  "Aprecie cada refeição com gratidão e consciência.",
  "Adote uma abordagem holística para sua saúde alimentar.",
  "A verdadeira riqueza está na sua saúde.",
  "Seu corpo é seu templo, cuide bem dele.",
  "O poder está nas pequenas mudanças diárias.",
  "Mantenha-se hidratado para um funcionamento ideal do corpo.",
  "O bem-estar começa na geladeira e na despensa.",
  "Desfrute de cada sabor sem culpa, mas com moderação.",
  "Respeite sua fome e saciedade.",
  "Faça escolhas que alimentem não apenas seu corpo, mas também sua mente.",
  "Uma dieta equilibrada é uma forma de autoamor.",
  "Cuide da sua saúde hoje para colher os benefícios amanhã.",
  "Fuja das dietas da moda, busque um estilo de vida sustentável.",
  "Comida de verdade para uma vida verdadeira.",
  "O alimento é o remédio mais poderoso.",
  "Dê preferência aos alimentos integrais e não processados.",
  "A qualidade da sua saúde reflete a qualidade da sua dieta.",
  "Desafie-se a experimentar novos alimentos e sabores.",
];
